CREATE TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE
  (	SERIEDOCUMENTAL_ID NUMBER(*,0),
	TIPUSDOCUMENTAL_ID NUMBER(*,0),
	OBLIGATORI NUMBER(1,0),
	MULTIPLE NUMBER(1,0)
   ) 
  TABLESPACE ARCHIUM;
  
COMMENT ON TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE  IS 'Tipus documentals de sèries no lligades a procediments administratius. Aquestes sèries produiran agrupacions documentals';

COMMENT ON COLUMN ARCHIUM.ACH_TIPUSDOCUMENT_SERIE.SERIEDOCUMENTAL_ID IS 'Identificador de la sèrie documental no procedimentada';
COMMENT ON COLUMN ARCHIUM.ACH_TIPUSDOCUMENT_SERIE.TIPUSDOCUMENTAL_ID IS 'Identificador del tipus documental a emprar a les agrupacions';
COMMENT ON COLUMN ARCHIUM.ACH_TIPUSDOCUMENT_SERIE.OBLIGATORI IS 'Indicador de si el tipus documental és obligatori a totes les agrupacions de la sèrie';
COMMENT ON COLUMN ARCHIUM.ACH_TIPUSDOCUMENT_SERIE.MULTIPLE IS 'Indicador de si el tipus documental pot aparèixer múltiples vegades a la mateixa agrupació';

CREATE UNIQUE INDEX ARCHIUM.ACH_TIPDOC_SERIE_PK ON ARCHIUM.ACH_TIPUSDOCUMENT_SERIE (SERIEDOCUMENTAL_ID, TIPUSDOCUMENTAL_ID)
  TABLESPACE ARCHIUM;

 
CREATE INDEX ARCHIUM.ACH_TIPDOC_SER_SER_FK_I ON ARCHIUM.ACH_TIPUSDOCUMENT_SERIE (SERIEDOCUMENTAL_ID)
  TABLESPACE ARCHIUM;

 
CREATE INDEX ARCHIUM.ACH_TIPDOC_SER_TIPDOC_FK_I ON ARCHIUM.ACH_TIPUSDOCUMENT_SERIE (TIPUSDOCUMENTAL_ID)
  TABLESPACE ARCHIUM;
  
ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE MODIFY (SERIEDOCUMENTAL_ID NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE MODIFY (TIPUSDOCUMENTAL_ID NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE MODIFY (OBLIGATORI NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE MODIFY (MULTIPLE NOT NULL ENABLE);

ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE ADD CONSTRAINT ACH_TIPDOC_SERIE_PK PRIMARY KEY (SERIEDOCUMENTAL_ID, TIPUSDOCUMENTAL_ID)
  USING INDEX TABLESPACE ARCHIUM  ENABLE;

ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE ADD CONSTRAINT ACH_TIPDOCSER_SER_FK FOREIGN KEY (SERIEDOCUMENTAL_ID)
	  REFERENCES ARCHIUM.ACH_SERIEDOCUMENTAL (ID) ENABLE;

ALTER TABLE ARCHIUM.ACH_TIPUSDOCUMENT_SERIE ADD CONSTRAINT ACH_TIPDOCSER_TDO_FK FOREIGN KEY (TIPUSDOCUMENTAL_ID)
	  REFERENCES ARCHIUM.ACH_TIPUSDOCUMENTAL (ID) ENABLE;
  
GRANT SELECT, UPDATE, INSERT, DELETE ON ARCHIUM.ACH_TIPUSDOCUMENT_SERIE TO WWW_ARCHIUM;