CREATE SEQUENCE  ARCHIUM.ACH_ORGANCOLLEGIAT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE ARCHIUM.ACH_ORGANCOLLEGIAT
   (ID NUMBER(*,0),
    CODI VARCHAR2(200 CHAR),
	NOM VARCHAR2(2000 CHAR)
   ) TABLESPACE ARCHIUM;

CREATE UNIQUE INDEX ARCHIUM.ACH_ORGANCOLLEGIAT_PK ON ARCHIUM.ACH_ORGANCOLLEGIAT (ID)
  TABLESPACE ARCHIUM;

CREATE UNIQUE INDEX ARCHIUM.ACH_ORGANCOLLEGIAT_CODI_UK ON ARCHIUM.ACH_ORGANCOLLEGIAT (CODI)
  TABLESPACE ARCHIUM;

ALTER TABLE ARCHIUM.ACH_ORGANCOLLEGIAT MODIFY (ID NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_ORGANCOLLEGIAT MODIFY (CODI NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_ORGANCOLLEGIAT MODIFY (NOM NOT NULL ENABLE);

ALTER TABLE ARCHIUM.ACH_ORGANCOLLEGIAT ADD CONSTRAINT ACH_ORGANCOLLEGIAT_PK PRIMARY KEY (ID)
  USING INDEX TABLESPACE ARCHIUM  ENABLE;

GRANT SELECT ON ARCHIUM.ACH_ORGANCOLLEGIAT_SEQ TO WWW_ARCHIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON ARCHIUM.ACH_ORGANCOLLEGIAT TO WWW_ARCHIUM;