ALTER TABLE ACH_SERIEDOCUMENTAL ADD ORGANCOLLEGIAT_ID NUMBER(*,0);

COMMENT ON COLUMN ACH_SERIEDOCUMENTAL.ORGANCOLLEGIAT_ID IS 'Referència opcional a l''òrgan col·legiat productor de la sèrie';

ALTER TABLE ARCHIUM.ACH_SERIEDOCUMENTAL ADD CONSTRAINT ACH_SER_ORGCOL_FK FOREIGN KEY (ORGANCOLLEGIAT_ID)
	  REFERENCES ARCHIUM.ACH_ORGANCOLLEGIAT (ID) ENABLE;

CREATE INDEX ARCHIUM.ACH_SERIE_ORGCOL_FK_I ON ARCHIUM.ACH_SERIEDOCUMENTAL (ORGANCOLLEGIAT_ID)
  TABLESPACE ARCHIUM;