CREATE TABLE ARCHIUM.ACH_TIPUSRELACIO
(	ID NUMBER(*,0), 
	CODI VARCHAR2(10 CHAR), 
	NOM  VARCHAR2(1000 CHAR), 
	NOMCAS  VARCHAR2(1000 CHAR),
	DESCRIPCIO VARCHAR2(4000 CHAR),	
	DESCRIPCIOCAS VARCHAR2(4000 CHAR)	
) TABLESPACE "ARCHIUM";


ALTER TABLE ARCHIUM.ACH_TIPUSRELACIO MODIFY (ID NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSRELACIO MODIFY (CODI NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSRELACIO MODIFY (NOM NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_TIPUSRELACIO ADD CONSTRAINT "ACH_TIPUSRELACIO_PK" PRIMARY KEY (ID);


CREATE SEQUENCE  ARCHIUM.ACH_TIPUSRELACIO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE;
