INSERT INTO ARCHIUM.ACH_TIPUSRELACIO(ID, CODI, NOM) VALUES (ACH_TIPUSRELACIO_SEQ.NEXTVAL, 'TEM', 'Temàtica');

INSERT INTO ARCHIUM.ACH_TIPUSRELACIO(ID, CODI, NOM) VALUES (ACH_TIPUSRELACIO_SEQ.NEXTVAL, 'RCP', 'Recapitulació');

