ALTER TABLE ARCHIUM.ACH_SERIERELACIONADA MODIFY (TIPUSRELACIO_ID NOT NULL ENABLE);



ALTER TABLE ARCHIUM.ACH_SERIERELACIONADA ADD CONSTRAINT ACH_SERRELA_TIPREL_FK FOREIGN KEY (TIPUSRELACIO_ID)
	  REFERENCES ARCHIUM.ACH_TIPUSRELACIO (ID) ENABLE;

