CREATE TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE 
(	SERIEDOCUMENTAL_ID NUMBER(*,0), 
	PROCEDIMENT_ID NUMBER(*,0)
) TABLESPACE ARCHIUM;

COMMENT ON TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE  IS 'Permet mantenir el vincle possible entre procediments comuns i les múltiples sèries a les quals pot anar';

CREATE UNIQUE INDEX ARCHIUM.ACH_PROCEDIMENT_SERIE_PK ON ARCHIUM.ACH_PROCEDIMENT_SERIE (SERIEDOCUMENTAL_ID, PROCEDIMENT_ID) 
  TABLESPACE ARCHIUM;
  
CREATE INDEX ARCHIUM.ACH_PRCSER_SER_FK_I ON ARCHIUM.ACH_PROCEDIMENT_SERIE (SERIEDOCUMENTAL_ID) 
  TABLESPACE ARCHIUM;

CREATE INDEX ARCHIUM.ACH_PRCSER_PRC_FK_I ON ARCHIUM.ACH_PROCEDIMENT_SERIE (PROCEDIMENT_ID) 
  TABLESPACE ARCHIUM;  
  
ALTER TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE MODIFY (SERIEDOCUMENTAL_ID NOT NULL ENABLE);
ALTER TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE MODIFY (PROCEDIMENT_ID NOT NULL ENABLE);

ALTER TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE ADD CONSTRAINT ACH_PROCEDIMENT_SERIE_PK PRIMARY KEY (SERIEDOCUMENTAL_ID, PROCEDIMENT_ID); 

ALTER TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE ADD CONSTRAINT ACH_PRCSER_SER_FK FOREIGN KEY (SERIEDOCUMENTAL_ID)
	  REFERENCES ARCHIUM.ACH_SERIEDOCUMENTAL (ID) ENABLE;
	  
ALTER TABLE ARCHIUM.ACH_PROCEDIMENT_SERIE ADD CONSTRAINT ACH_PRCSER_PRC_FK FOREIGN KEY (PROCEDIMENT_ID)
	  REFERENCES ARCHIUM.ACH_PROCEDIMENT (ID) ENABLE;  
  
GRANT SELECT, UPDATE, INSERT, DELETE ON ARCHIUM.ACH_PROCEDIMENT_SERIE TO WWW_ARCHIUM;
