ALTER TABLE ACH_SERIEDOCUMENTAL ADD SYNCHRONIZED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE ACH_SERIEDOCUMENTAL ADD NODEID VARCHAR2(50 BYTE);

ALTER TABLE ACH_FUNCIO ADD SYNCHRONIZED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE ACH_FUNCIO ADD NODEID VARCHAR2(50 BYTE);

ALTER TABLE ACH_QUADRECLASSIFICACIO ADD SYNCHRONIZED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE ACH_QUADRECLASSIFICACIO ADD NODEID VARCHAR2(50 BYTE);


ALTER TABLE ARCHIUM.ACH_BUTLLETI MODIFY CODI CHAR(6 BYTE);
ALTER TABLE ARCHIUM.ACH_BUTLLETI MODIFY NOM CHAR(200 BYTE);
ALTER TABLE ARCHIUM.ACH_BUTLLETI MODIFY DESCRIPCIO CHAR(2000 BYTE);


ALTER TABLE ARCHIUM.ACH_DICTAMEN MODIFY ESTAT CHAR(12 BYTE);
ALTER TABLE ARCHIUM.ACH_DICTAMEN MODIFY CODI CHAR(10 BYTE);


ALTER TABLE ARCHIUM.ACH_TIPUSNORMATIVA MODIFY NOM CHAR(200 BYTE);


COMMENT ON TABLE "ARCHIUM"."ACH_DICTAMEN"  IS '';
COMMENT ON COLUMN "ARCHIUM"."ACH_DICTAMEN"."CODI" IS 'Codi seqüencial que, idealment, hauria de començar pel següent valor de les taules de valoració ARGEN (actualment, 26/03/2020, seria valor 265)';


ALTER TABLE "ARCHIUM"."ACH_CAUSALIMITACIO" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_ENS" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_LOPD" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_TIPUSACCES" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_TIPUSDICTAMEN" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_TIPUSSERIE" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_TIPUSVALOR" MODIFY ("NOMCAS" NOT NULL ENABLE);
ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" ADD CONSTRAINT "QTD_NOM_UNIQUE" UNIQUE("NOM");


UPDATE "ARCHIUM"."ACH_VALORSECUNDARI" SET NOMCAS = 'Sí' WHERE NOM = 'Sí';
UPDATE "ARCHIUM"."ACH_VALORSECUNDARI" SET NOMCAS = 'No' WHERE NOM = 'No';
UPDATE "ARCHIUM"."ACH_VALORSECUNDARI" SET NOMCAS = 'Sin cobertura de calificación' WHERE NOM = 'Sense cobertura de qualificació';
ALTER TABLE "ARCHIUM"."ACH_VALORSECUNDARI" MODIFY ("NOMCAS" NOT NULL ENABLE);

ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("NOMCAS" NOT NULL ENABLE);

commit;