ALTER TABLE ACH_NORMATIVA 
ADD CONSTRAINT FK_BUTLLETI 
FOREIGN KEY (BUTLLETI_ID) 
REFERENCES ACH_BUTLLETI(ID);

ALTER TABLE ACH_NORMATIVA 
ADD CONSTRAINT FK_TIPUS_NORMATIVA
FOREIGN KEY (TIPUSNORMATIVA_ID) 
REFERENCES ACH_TIPUSNORMATIVA(ID);