
  CREATE UNIQUE INDEX "ARCHIUM"."ACH_APLICACIO_PK" ON "ARCHIUM"."ACH_APLICACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_APLICA_SERIE_APLICA_FK_I" ON "ARCHIUM"."ACH_APLICACIO_SERIE" ("APLICACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_APLICACIO_SERIE_PK" ON "ARCHIUM"."ACH_APLICACIO_SERIE" ("SERIEDOCUMENTAL_ID", "APLICACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_APLICA_SERIE_SERIEDOC_FK_I" ON "ARCHIUM"."ACH_APLICACIO_SERIE" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_CATALEGSERIES_PK" ON "ARCHIUM"."ACH_CATALEGSERIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_CATEGORIANTI_PK" ON "ARCHIUM"."ACH_CATEGORIANTI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_CAUSALIMITACIO_PK" ON "ARCHIUM"."ACH_CAUSALIMITACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT_PK" ON "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ("PROCEDIMENT_ID", "TIPUSCONTACTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_CONTAC_PROCED_PROCED_FK_I" ON "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ("PROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_CONTAC_PROC_TIPCON_FK_I" ON "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ("TIPUSCONTACTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_DICTAMEN_ENS_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("ENS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_DICTAMEN_LOPD_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("LOPD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_DICTAMEN_NORMATIVA_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("NORMATIVA_APROVACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_DICTAMEN_PK" ON "ARCHIUM"."ACH_DICTAMEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_DICT_SERIEDOCUMENT_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_DICTAMEN_TIPUSACCES_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("TIPUSACCES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_DICT_TIPUSDICT1_FK_I" ON "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ("TIPUSDICTAMEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_DICT_TIPUSDICT2_FK_I" ON "ARCHIUM"."ACH_DICTAMEN" ("TIPUSDICTAMEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ON "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ("DICTAMEN_ID", "TIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_DICT_TIPDOCUMENT_DICT_FK_I" ON "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ("DICTAMEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_DICT_TIPDOCU_TIPDOCU_FK_I" ON "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ("TIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_ENS_PK" ON "ARCHIUM"."ACH_ENS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_FAMILIAPROCEDIMENT_PK" ON "ARCHIUM"."ACH_FAMILIAPROCEDIMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_FASEARXIU_PK" ON "ARCHIUM"."ACH_FASEARXIU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_FORMAINICI_PK" ON "ARCHIUM"."ACH_FORMAINICI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_FUNCIO_FUNCIO_FK_I" ON "ARCHIUM"."ACH_FUNCIO" ("FUNCIO_PARE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_FUNCIO_PK" ON "ARCHIUM"."ACH_FUNCIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_FUN_QUADCLASSIFI_FK_I" ON "ARCHIUM"."ACH_FUNCIO" ("QUADRECLASSIFICACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_FUNCIO_TIPUSSERIE_FK_I" ON "ARCHIUM"."ACH_FUNCIO" ("TIPUSSERIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_LIM_NOR_SER_CAULIM_FK_I" ON "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ("CAUSALIMITACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_LIM_NOR_SER_NOR_FK_I" ON "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ("NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE UNIQUE INDEX "ARCHIUM"."ACH_LIM_NOR_SER_PK" ON "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ("SERIEDOCUMENTAL_ID", "NORMATIVA_ID", "CAUSALIMITACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_LIM_NOR_SER_SERDOC_FK_I" ON "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_MATERIA_PK" ON "ARCHIUM"."ACH_MATERIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_MATERIA_PROCEDIMENT_FK1_I" ON "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ("PROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_MATERIA_PROCEDIMENT_FK2_I" ON "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ("MATERIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_MATERIA_PROCEDIMENT_PK" ON "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ("PROCEDIMENT_ID", "MATERIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NIVELLELECTRONIC_PK" ON "ARCHIUM"."ACH_NIVELLELECTRONIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_DIC_DIC_FK_I" ON "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ("DICTAMEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_DIC_NOR_FK_I" ON "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ("NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NORMATIVA_DICTAMEN_PK" ON "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ("DICTAMEN_ID", "NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_NORMATIVA_NORMATIVA_FK_I" ON "ARCHIUM"."ACH_NORMATIVA" ("NORMATIVA_VIGENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NORMATIVA_PK" ON "ARCHIUM"."ACH_NORMATIVA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;
  
 
  CREATE INDEX "ARCHIUM"."ACH_NOR_PRO_NOR_I" ON "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ("NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT_PK" ON "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ("PROCEDIMENT_ID", "NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_PRO_PRO_FK_I" ON "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ("PROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_SERDOC_NOR_FK_I" ON "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ("NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NOR_SERDOC_PK" ON "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ("SERIEDOCUMENTAL_ID", "NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_SERDOC_SERDOC_FK_I" ON "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE UNIQUE INDEX "ARCHIUM"."ACH_NOR_TIPDOC_PK" ON "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ("TIPUSDOCUMENTAL_ID", "NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_TIPDOC1_PK_I" ON "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ("TIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_NOR_TIPDOC2_PK_I" ON "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ("NORMATIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;


  CREATE INDEX "ARCHIUM"."ACH_PROCEDIMENT_APLICACIO_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("APLICACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_PRO_FAM_PROC_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("FAMILIAPROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_PROC_FORMAINI_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("FORMAINICI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_PROC_NIVELELECT_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("NIVELLELECTRONIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_PROCEDIMENT_PK" ON "ARCHIUM"."ACH_PROCEDIMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_PROC_SERDOC_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE INDEX "ARCHIUM"."ACH_PROCEDIMENT_SILENCI_FK_I" ON "ARCHIUM"."ACH_PROCEDIMENT" ("SILENCI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_QUADRECLASSIFICACIO_PK" ON "ARCHIUM"."ACH_QUADRECLASSIFICACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL_PK" ON "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_SERIEARGEN_PK" ON "ARCHIUM"."ACH_SERIEARGEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERDOC_CATSER_FK_I" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("CATALEGSERIES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERDOC_FUN_FK_I" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("FUNCIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ("SERIEDOCUMENTAL_ID", "SERIEARGEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERDOC_MIGRA_SERARGEN_FK_I" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ("SERIEARGEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERDOC_MIGR_SERDOC_FK_I" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_SERIEDOCUMENTAL_PK" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERDOC_TIPSER_FK_I" ON "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("TIPUSSERIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_SERIERELACIONADA_PK" ON "ARCHIUM"."ACH_SERIERELACIONADA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERREL_SERARGEN_FK_I" ON "ARCHIUM"."ACH_SERIERELACIONADA" ("SERIEARGEN_RELACIONADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERRELA_SERDOC1_FK_I" ON "ARCHIUM"."ACH_SERIERELACIONADA" ("SERIEDOCUMENTAL_ID")   
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_SERREL_SERDOC2_FK_I" ON "ARCHIUM"."ACH_SERIERELACIONADA" ("SERIE_RELACIONADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_SILENCI_PK" ON "ARCHIUM"."ACH_SILENCI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSCONTACTE_PK" ON "ARCHIUM"."ACH_TIPUSCONTACTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSDICTAMEN_PK" ON "ARCHIUM"."ACH_TIPUSDICTAMEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSDOCUMENTAL_CODI_PK" ON "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSDOCUMENTAL_PK" ON "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPDOC_QUADTIPDOC_FK_I" ON "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("QUADRETIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPDOC_TIPNTI_FK_I" ON "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("TIPUSNTI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPDOC_PROC_PK" ON "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ("PROCEDIMENT_ID", "TIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPDOC_PROC_PROC_FK_I" ON "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ("PROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPDOC_PRO_TIPDOC_FK_I" ON "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ("TIPUSDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPNTI_CATENTI_ID_FK_I" ON "ARCHIUM"."ACH_TIPUSNTI" ("CATEGORIANTI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSNTI_PK" ON "ARCHIUM"."ACH_TIPUSNTI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSPUBLIC_PK" ON "ARCHIUM"."ACH_TIPUSPUBLIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT_PK" ON "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ("PROCEDIMENT_ID", "TIPUSPUBLIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPPUBLIC_PROC_PROC1_FK_I" ON "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ("PROCEDIMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TIPPUBLIC_PROC_PROC2_FK_I" ON "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ("TIPUSPUBLIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSSERIE_PK" ON "ARCHIUM"."ACH_TIPUSSERIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSVALOR_PK" ON "ARCHIUM"."ACH_TIPUSVALOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TRANS_FASARXIU_FK_I" ON "ARCHIUM"."ACH_TRANSFERENCIA" ("FASEARXIU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TRANSFERENCIA_PK" ON "ARCHIUM"."ACH_TRANSFERENCIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_TRANS_SERDOC_FK_I" ON "ARCHIUM"."ACH_TRANSFERENCIA" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_VALORACIO_PK" ON "ARCHIUM"."ACH_VALORACIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_VALOR_SERDOC_FK_I" ON "ARCHIUM"."ACH_VALORACIO" ("SERIEDOCUMENTAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_VAL_VALSEC_FK_I" ON "ARCHIUM"."ACH_VALORACIO" ("VALORSECUNDARI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_VALORPRIMARI_PK" ON "ARCHIUM"."ACH_VALORPRIMARI" ("VALORACIO_ID", "TIPUSVALOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_VALPRIM_TIPVALOR_FK_I" ON "ARCHIUM"."ACH_VALORPRIMARI" ("TIPUSVALOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

 
  CREATE INDEX "ARCHIUM"."ACH_VALPRIM_VALOR_FK_I" ON "ARCHIUM"."ACH_VALORPRIMARI" ("VALORACIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_VALORSECUNDARI_PK" ON "ARCHIUM"."ACH_VALORSECUNDARI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_LOPD_PK" ON "ARCHIUM"."ACH_LOPD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_TIPUSACCES_PK" ON "ARCHIUM"."ACH_TIPUSACCES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_butlleti_PK" ON "ARCHIUM"."ACH_BUTLLETI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;

  CREATE UNIQUE INDEX "ARCHIUM"."ACH_tipusnormativa_PK" ON "ARCHIUM"."ACH_TIPUSNORMATIVA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM" ;