
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" MODIFY ("PERFIL" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO" ADD CONSTRAINT "ACH_APLICACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" MODIFY ("APLICACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" ADD CONSTRAINT "ACH_APLICACIO_SERIE_PK" PRIMARY KEY ("SERIEDOCUMENTAL_ID", "APLICACIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_BUTLLETI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_BUTLLETI" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_BUTLLETI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_BUTLLETI" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_BUTLLETI" ADD CONSTRAINT "ACH_butlleti_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" MODIFY ("VERSIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATALEGSERIES" ADD CONSTRAINT "ACH_CATALEGSERIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_CATEGORIANTI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATEGORIANTI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CATEGORIANTI" ADD CONSTRAINT "ACH_CATEGORIANTI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_CAUSALIMITACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CAUSALIMITACIO" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CAUSALIMITACIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CAUSALIMITACIO" ADD CONSTRAINT "ACH_CAUSALIMITACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" MODIFY ("CONTACTE" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" MODIFY ("TIPUSCONTACTE_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ADD CONSTRAINT "ACH_CONTACTE_PROCEDIMENT_PK" PRIMARY KEY ("PROCEDIMENT_ID", "TIPUSCONTACTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICTAMEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" MODIFY ("CODI" NOT NULL ENABLE);

  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" MODIFY ("DICTAMEN_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" MODIFY ("TIPUSDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" MODIFY ("TIPUSDICTAMEN_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" MODIFY ("CONSERVABLE" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_DICTAMEN_TIPUSDOCUMENTAL" PRIMARY KEY ("DICTAMEN_ID", "TIPUSDOCUMENTAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_ENS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_ENS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_ENS" ADD CONSTRAINT "ACH_ENS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_FAMILIAPROCEDIMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FAMILIAPROCEDIMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FAMILIAPROCEDIMENT" ADD CONSTRAINT "ACH_FAMILIAPROCEDIMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_FASEARXIU" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FASEARXIU" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FASEARXIU" ADD CONSTRAINT "ACH_FASEARXIU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_FORMAINICI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FORMAINICI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FORMAINICI" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FORMAINICI" ADD CONSTRAINT "ACH_FORMAINICI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("QUADRECLASSIFICACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("ORDRE" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" MODIFY ("MODIFICACIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" ADD CONSTRAINT "ACH_FUNCIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" MODIFY ("NORMATIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" MODIFY ("CAUSALIMITACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ADD CONSTRAINT "ACH_LIM_NOR_SER_PK" PRIMARY KEY ("SERIEDOCUMENTAL_ID", "NORMATIVA_ID", "CAUSALIMITACIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_LOPD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LOPD" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_LOPD" ADD CONSTRAINT "ACH_LOPD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_MATERIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_MATERIA" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_MATERIA" ADD CONSTRAINT "ACH_MATERIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" MODIFY ("MATERIA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ADD CONSTRAINT "ACH_MATERIA_PROCEDIMENT_PK" PRIMARY KEY ("PROCEDIMENT_ID", "MATERIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NIVELLELECTRONIC" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NIVELLELECTRONIC" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NIVELLELECTRONIC" ADD CONSTRAINT "ACH_NIVELLELECTRONIC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA" ADD CONSTRAINT "ACH_NORMATIVA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" MODIFY ("DICTAMEN_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" MODIFY ("NORMATIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ADD CONSTRAINT "ACH_NORMATIVA_DICTAMEN_PK" PRIMARY KEY ("DICTAMEN_ID", "NORMATIVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" MODIFY ("NORMATIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ADD CONSTRAINT "ACH_NORMATIVA_PROCEDIMENT_PK" PRIMARY KEY ("PROCEDIMENT_ID", "NORMATIVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" MODIFY ("NORMATIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_SERDOC_PK" PRIMARY KEY ("SERIEDOCUMENTAL_ID", "NORMATIVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" MODIFY ("TIPUSDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" MODIFY ("NORMATIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_TIPDOC_PK" PRIMARY KEY ("TIPUSDOCUMENTAL_ID", "NORMATIVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" MODIFY ("OBJECTE" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROCEDIMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" MODIFY ("MODIFICACIO" NOT NULL ENABLE);

  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("MODIFICACIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" MODIFY ("VERSIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" ADD CONSTRAINT "QUADRE_NOM_UNIQUE" UNIQUE("NOM");
  ALTER TABLE "ARCHIUM"."ACH_QUADRECLASSIFICACIO" ADD CONSTRAINT "ACH_QUADRECLASSIFICACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("MODIFICACIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" MODIFY ("VERSIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_QUADRETIPUSDOCUMENTAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIEARGEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEARGEN" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEARGEN" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEARGEN" ADD CONSTRAINT "ACH_SERIEARGEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("CATALEGSERIES_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_SERIEDOCUMENTAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" MODIFY ("SERIEARGEN_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ADD CONSTRAINT "ACH_SERIEDOCUMENTAL_MIGRACIO" PRIMARY KEY ("SERIEDOCUMENTAL_ID", "SERIEARGEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" ADD CONSTRAINT "ACH_SERIERELACIONADA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SILENCI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SILENCI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_SILENCI" ADD CONSTRAINT "ACH_SILENCI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSACCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSACCES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSACCES" ADD CONSTRAINT "ACH_TIPUSACCES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSCONTACTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSCONTACTE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSCONTACTE" ADD CONSTRAINT "ACH_TIPUSCONTACTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSDICTAMEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDICTAMEN" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDICTAMEN" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDICTAMEN" ADD CONSTRAINT "ACH_TIPUSDICTAMEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("QUADRETIPUSDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("TIPUSNTI_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("DEFINICIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("MODIFICACIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" MODIFY ("ESTAT" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_TIPUSDOCUMENTAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_TIPUSDOCUMENTAL_CODI_PK" UNIQUE ("CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" MODIFY ("TIPUSDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" MODIFY ("OBLIGATORI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" MODIFY ("RECAPITULATIU" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPDOC_PROC_PK" PRIMARY KEY ("PROCEDIMENT_ID", "TIPUSDOCUMENTAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSNORMATIVA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNORMATIVA" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNORMATIVA" ADD CONSTRAINT "ACH_tipusnormativa_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" MODIFY ("CODI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" MODIFY ("CATEGORIANTI_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" ADD CONSTRAINT "ACH_TIPUSNTI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC" MODIFY ("DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC" ADD CONSTRAINT "ACH_TIPUSPUBLIC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" MODIFY ("TIPUSPUBLIC_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPUSPUBLIC_PROCEDIMENT_PK" PRIMARY KEY ("PROCEDIMENT_ID", "TIPUSPUBLIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSSERIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSSERIE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSSERIE" ADD CONSTRAINT "ACH_TIPUSSERIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSVALOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSVALOR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TIPUSVALOR" ADD CONSTRAINT "ACH_TIPUSVALOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" MODIFY ("FASEARXIU_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" MODIFY ("TERMINI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" ADD CONSTRAINT "ACH_TRANSFERENCIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" MODIFY ("SERIEDOCUMENTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" MODIFY ("VALORSECUNDARI_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" MODIFY ("INICI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" ADD CONSTRAINT "ACH_VALORACIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" MODIFY ("VALORACIO_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" MODIFY ("TERMINI" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" MODIFY ("TIPUSVALOR_ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" ADD CONSTRAINT "ACH_VALORPRIMARI_PK" PRIMARY KEY ("VALORACIO_ID", "TIPUSVALOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_VALORSECUNDARI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORSECUNDARI" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ARCHIUM"."ACH_VALORSECUNDARI" ADD CONSTRAINT "ACH_VALORSECUNDARI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCHIUM"  ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" ADD CONSTRAINT "ACH_APLICA_SERIE_SERIEDOC_FK_I" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_APLICACIO_SERIE" ADD CONSTRAINT "ACH_APLICA_SERIE_APLICA_FK_" FOREIGN KEY ("APLICACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_APLICACIO" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ADD CONSTRAINT "ACH_CONTAC_PROCED_PROCED_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_PROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_CONTACTE_PROCEDIMENT" ADD CONSTRAINT "ACH_CONTAC_PROCED_TIPCONTAC_FK" FOREIGN KEY ("TIPUSCONTACTE_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSCONTACTE" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICT_SERIEDOCUMENT_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICT_TIPUSDICT_FK" FOREIGN KEY ("TIPUSDICTAMEN_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSDICTAMEN" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICTAMEN_TIPUSACCES_FK" FOREIGN KEY ("TIPUSACCES_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSACCES" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICTAMEN_ENS_FK" FOREIGN KEY ("ENS_ID")
	  REFERENCES "ARCHIUM"."ACH_ENS" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICTAMEN_LOPD_FK" FOREIGN KEY ("LOPD_ID")
	  REFERENCES "ARCHIUM"."ACH_LOPD" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN" ADD CONSTRAINT "ACH_DICTAMEN_NORMATIVA_FK" FOREIGN KEY ("NORMATIVA_APROVACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_DICT_TIPDOCUMENT_DICT_FK" FOREIGN KEY ("DICTAMEN_ID")
	  REFERENCES "ARCHIUM"."ACH_DICTAMEN" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_DICT_TIPDOCU_TIPDOCU_FK" FOREIGN KEY ("TIPUSDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_DICTAMEN_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_DIC_TIPDOC_TIPDIC_FK" FOREIGN KEY ("TIPUSDICTAMEN_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSDICTAMEN" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" ADD CONSTRAINT "ACH_FUNCIO_FUNCIO_FK" FOREIGN KEY ("FUNCIO_PARE")
	  REFERENCES "ARCHIUM"."ACH_FUNCIO" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" ADD CONSTRAINT "ACH_FUN_QUADCLASSIFI_FK" FOREIGN KEY ("QUADRECLASSIFICACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_QUADRECLASSIFICACIO" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_FUNCIO" ADD CONSTRAINT "ACH_FUNCIO_TIPUSSERIE_FK" FOREIGN KEY ("TIPUSSERIE_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSSERIE" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ADD CONSTRAINT "ACH_LIM_NOR_SER_SERDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ADD CONSTRAINT "ACH_LIM_NOR_SER_NOR_FK" FOREIGN KEY ("NORMATIVA_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_LIMITACIO_NORMATIVA_SERIE" ADD CONSTRAINT "ACH_LIM_NOR_SER_CAULIM_FK" FOREIGN KEY ("CAUSALIMITACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_CAUSALIMITACIO" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ADD CONSTRAINT "ACH_MAT_PRO_PRO_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_PROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_MATERIA_PROCEDIMENT" ADD CONSTRAINT "ACH_MAT_PRO_MAT_FK" FOREIGN KEY ("MATERIA_ID")
	  REFERENCES "ARCHIUM"."ACH_MATERIA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA" ADD CONSTRAINT "ACH_NORMATIVA_NORMATIVA_FK" FOREIGN KEY ("NORMATIVA_VIGENT")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ADD CONSTRAINT "ACH_NOR_DIC_DIC_FK" FOREIGN KEY ("DICTAMEN_ID")
	  REFERENCES "ARCHIUM"."ACH_DICTAMEN" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_DICTAMEN" ADD CONSTRAINT "ACH_NOR_DIC_NOR_FK" FOREIGN KEY ("NORMATIVA_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ADD CONSTRAINT "ACH_NOR_PRO_PRO_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_PROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_PROCEDIMENT" ADD CONSTRAINT "ACH_NOR_PRO_NOR" FOREIGN KEY ("NORMATIVA_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_SERDOC_SERDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_SERDOC_NOR_FK" FOREIGN KEY ("NORMATIVA_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_TIPDOC_TIPDOC_FK" FOREIGN KEY ("TIPUSDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_NORMATIVA_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_NOR_TIPDOC_NOR" FOREIGN KEY ("NORMATIVA_ID")
	  REFERENCES "ARCHIUM"."ACH_NORMATIVA" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PRO_FAM_PROC_FK" FOREIGN KEY ("FAMILIAPROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_FAMILIAPROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROC_FORMAINI_FK" FOREIGN KEY ("FORMAINICI_ID")
	  REFERENCES "ARCHIUM"."ACH_FORMAINICI" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROCEDIMENT_SILENCI_FK" FOREIGN KEY ("SILENCI_ID")
	  REFERENCES "ARCHIUM"."ACH_SILENCI" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROC_NIVELELECT_FK" FOREIGN KEY ("NIVELLELECTRONIC_ID")
	  REFERENCES "ARCHIUM"."ACH_NIVELLELECTRONIC" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROCEDIMENT_SERIEDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_PROCEDIMENT" ADD CONSTRAINT "ACH_PROCEDIMENT_APLICACIO_FK" FOREIGN KEY ("APLICACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_APLICACIO" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_SERIEDOCUMENTAL_FUNCIO_FK" FOREIGN KEY ("FUNCIO_ID")
	  REFERENCES "ARCHIUM"."ACH_FUNCIO" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_SERDOC_CATSER_FK" FOREIGN KEY ("CATALEGSERIES_ID")
	  REFERENCES "ARCHIUM"."ACH_CATALEGSERIES" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL" ADD CONSTRAINT "ACH_SERDOC_TIPSER_FK" FOREIGN KEY ("TIPUSSERIE_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSSERIE" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ADD CONSTRAINT "ACH_SERDOC_MIGR_SERDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_SERIEDOCUMENTAL_MIGRACIO" ADD CONSTRAINT "ACH_SERDOC_MIGRA_SERARGEN_FK" FOREIGN KEY ("SERIEARGEN_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEARGEN" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" ADD CONSTRAINT "ACH_SERRELA_SERDOC1_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" ADD CONSTRAINT "ACH_SERREL_SERDOC2_FK_I" FOREIGN KEY ("SERIE_RELACIONADA")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_SERIERELACIONADA" ADD CONSTRAINT "ACH_SERREL_SERARGEN_FK" FOREIGN KEY ("SERIEARGEN_RELACIONADA")
	  REFERENCES "ARCHIUM"."ACH_SERIEARGEN" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_TIPDOC_QUADTIPDOC_FK" FOREIGN KEY ("QUADRETIPUSDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_QUADRETIPUSDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ADD CONSTRAINT "ACH_TIPDOC_TIPNTI_FK" FOREIGN KEY ("TIPUSNTI_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSNTI" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPDOC_PROC_PROC_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_PROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_TIPUSDOCUMENT_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPDOC_PRO_TIPDOC_FK" FOREIGN KEY ("TIPUSDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSDOCUMENTAL" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSNTI" ADD CONSTRAINT "ACH_TIPUSNTI_CATEGORIANTI_FK" FOREIGN KEY ("CATEGORIANTI_ID")
	  REFERENCES "ARCHIUM"."ACH_CATEGORIANTI" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPPUBLIC_PROC_PROC_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "ARCHIUM"."ACH_PROCEDIMENT" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_TIPUSPUBLIC_PROCEDIMENT" ADD CONSTRAINT "ACH_TIPPUB_PROC_TIPPUB_FK" FOREIGN KEY ("TIPUSPUBLIC_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSPUBLIC" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" ADD CONSTRAINT "ACH_TRANS_SERDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_TRANSFERENCIA" ADD CONSTRAINT "ACH_TRANSFERENCIA_FASEARXIU" FOREIGN KEY ("FASEARXIU_ID")
	  REFERENCES "ARCHIUM"."ACH_FASEARXIU" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" ADD CONSTRAINT "ACH_VALOR_SERDOC_FK" FOREIGN KEY ("SERIEDOCUMENTAL_ID")
	  REFERENCES "ARCHIUM"."ACH_SERIEDOCUMENTAL" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_VALORACIO" ADD CONSTRAINT "ACH_VAL_VALSEC_FK" FOREIGN KEY ("VALORSECUNDARI_ID")
	  REFERENCES "ARCHIUM"."ACH_VALORSECUNDARI" ("ID") ENABLE;

  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" ADD CONSTRAINT "ACH_VALORPRIMARI_VALORACIO_FK" FOREIGN KEY ("VALORACIO_ID")
	  REFERENCES "ARCHIUM"."ACH_VALORACIO" ("ID") ENABLE;
  ALTER TABLE "ARCHIUM"."ACH_VALORPRIMARI" ADD CONSTRAINT "ACH_VALORPRIMARI_TIPUSVALOR_FK" FOREIGN KEY ("TIPUSVALOR_ID")
	  REFERENCES "ARCHIUM"."ACH_TIPUSVALOR" ("ID") ENABLE;
